# Generated by Django 4.0.3 on 2022-03-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnumber', models.CharField(max_length=20)),
                ('runningdays', models.CharField(max_length=30)),
                ('carstartlocation', models.CharField(max_length=30)),
                ('carsecondlocation', models.CharField(max_length=30)),
                ('availableSeatsStop1', models.IntegerField(default=0)),
                ('carthridlocation', models.CharField(max_length=30)),
                ('availableSeatsStop2', models.IntegerField(default=0)),
                ('carfourthlocation', models.CharField(max_length=30)),
                ('availableSeatsStop3', models.IntegerField(default=0)),
                ('carendlocation', models.CharField(max_length=30)),
                ('availableSeatsStop4', models.IntegerField(default=0)),
                ('carstatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnumber', models.CharField(max_length=20)),
                ('runningdays', models.CharField(max_length=30)),
                ('startLocation', models.CharField(max_length=30)),
                ('nextLocation', models.CharField(max_length=30)),
                ('availSeat', models.IntegerField()),
                ('totalSeat', models.IntegerField()),
                ('active', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
